#theme: jekyll-theme-architect
remote_theme: "daviddarnes/alembic@main"
#minimal_mistakes_skin: "dirt"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme




